define({
	//generic page id's
	wrapper: document.getElementById('wrapper'),
	content: document.getElementById('content'),
	nav: document.getElementById('nav'),
	edit: document.getElementById('edit'),
	textArea: document.getElementById('textArea'),
	overlay: document.getElementById('ModalDialogueOverlay'),
	//Header icons
	upload: document.getElementById('imgUpload'),
	save: document.getElementById('imgSave'),
	logo: document.getElementById('imgLogo'),
	//div #nav icons
	codeIcon: document.getElementById('codeIcon'),
	hashIcon: document.getElementById('hashIcon'),
	boldIcon: document.getElementById('boldIcon'),
	italicsIcon: document.getElementById('italicsIcon'),
	underlineIcon: document.getElementById('underlineIcon'),
	strikeIcon: document.getElementById('strikeIcon'),
	fontStyle: document.getElementById('fontStyle'),
	fontSize: document.getElementById('fontSize'),
	cutIcon: document.getElementById('cutIcon'),
	copyIcon: document.getElementById('copyIcon'),
	pasteIcon: document.getElementById('pasteIcon'),
	undoIcon: document.getElementById('undoIcon'),
	redoIcon: document.getElementById('redoIcon'),
	subscriptIcon: document.getElementById('subscriptIcon'),
	superscriptIcon: document.getElementById('superscriptIcon'),
	changecaseIcon: document.getElementById('changecaseIcon'),
	fontcolorIcon: document.getElementById('fontcolorIcon'),
	backcolorIcon: document.getElementById('backcolorIcon'),
	insertimageIcon: document.getElementById('insertimageIcon'),
	insertvideoIcon: document.getElementById('insertvideoIcon'),
	linkIcon: document.getElementById('linkIcon'),
	alignleftIcon: document.getElementById('alignleftIcon'),
	alignrightIcon: document.getElementById('alignrightIcon'),
	aligncenterIcon: document.getElementById('aligncenterIcon'),
	justifyIcon: document.getElementById('justifyIcon'),
	hrIcon: document.getElementById('hrIcon'),
	ulIcon: document.getElementById('ulIcon'),
	olIcon: document.getElementById('olIcon'),
	indentIcon: document.getElementById('indentIcon'),
	outdentIcon: document.getElementById('outdentIcon'),
	linespacingIcon: document.getElementById('linespacingIcon'),
	tableIcon: document.getElementById('tableIcon'),
	settings: document.getElementById('settingsIcon')
})